/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Contact: typeof import('./pages/Contact.vue')['default']
    DarkModeToggle: typeof import('./components/DarkModeToggle.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    Home: typeof import('./components/Home.vue')['default']
    Input: typeof import('./components/Input.vue')['default']
    LanguageToggle: typeof import('./components/LanguageToggle.vue')['default']
    Navbar: typeof import('./components/Navbar.vue')['default']
    NavbarLink: typeof import('./components/NavbarLink.vue')['default']
    Profit: typeof import('./components/Profit.vue')['default']
    README: typeof import('./components/README.md')['default']
    Reviews: typeof import('./components/Reviews.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Slideshow: typeof import('./components/Slideshow.vue')['default']
    TheCounter: typeof import('./components/TheCounter.vue')['default']
    WhoWeAre: typeof import('./components/WhoWeAre.vue')['default']
  }
}
