/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BarChartComponent: typeof import('./components/charts/BarChartComponent.vue')['default']
    CompoundInterest: typeof import('./components/charts/CompoundInterest.vue')['default']
    CompoundProfit: typeof import('./components/charts/CompoundProfit.vue')['default']
    DarkModeToggle: typeof import('./components/DarkModeToggle.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    Home: typeof import('./components/Home.vue')['default']
    Input: typeof import('./components/Input.vue')['default']
    LanguageToggle: typeof import('./components/LanguageToggle.vue')['default']
    Navbar: typeof import('./components/Navbar.vue')['default']
    NavbarLink: typeof import('./components/NavbarLink.vue')['default']
    PieChartComponent: typeof import('./components/charts/PieChartComponent.vue')['default']
    README: typeof import('./components/README.md')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SimpleInterest: typeof import('./components/charts/SimpleInterest.vue')['default']
    Slideshow: typeof import('./components/Slideshow.vue')['default']
    TheCounter: typeof import('./components/TheCounter.vue')['default']
  }
}
